### ISSUE TITLE
Java version of termpura

### ISSUE THREAD

**Issue by SwiftyProgrammer690** [termpura/core#1]
Hi @rayhanadev. Is it okay if I work on a python and java version of it? Asking just in case you don't want me to make those for copyright reasons/etc ...

**Comment by rayhanadev** [comment]
By all means, go ahead! The principles behind Termpura were borrowed from Next.js 😂 so its entirely okay if you make your own version :). I wouldn't call it Termpura though, probably name and license your code with your own project name, that way its yours!

Good luck and looking forward to seeing more kewl TUIs on Github :D.

**Comment by SwiftyProgrammer690** [comment]
> By all means, go ahead! The principles behind Termpura were borrowed from Next.js 😂 so its entirely okay if you make your own version :). I wouldn't call it Termpura though, probably name and license your code with your own project name, that way its yours!
> 
> Good luck and looking forward to seeing more kewl TUIs on Github :D.

Alright! Also, I probably will name it jTermpura for java edition and pyTermpura for the python edition if that's okay with you...

**Comment by SwiftyProgrammer690** [comment]
Also thx for the quick reply!

**Comment by rayhanadev** [comment]
> Alright! Also, I probably will name it jTermpura for java edition and pyTermpura for the python edition if that's okay with you...

Perhaps not Termpura at all :). Something unique that you come up with 😌.

> Also thx for the quick reply!

No problem! :D
